import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container:          { flex: 1, backgroundColor: '#f5f5f5' },
    loadingContainer:   { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#fff' },
    loadingText:        { marginTop: 16, fontSize: 16, color: '#666' },
    header:             { paddingTop: 50, paddingBottom: 20, paddingHorizontal: 20 },
    headerTop:          { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    headerTitle:        { fontSize: 28, fontWeight: '800', color: '#fff' },
    headerSubtitle:     { fontSize: 14, color: 'rgba(255,255,255,0.8)' },
    headerActions:      { flexDirection: 'row', alignItems: 'center', gap: 8 },
    createAdminBtn:     { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7 },
    createAdminBtnText: { fontSize: 13, fontWeight: '700', color: '#6c2bd9' },
    logoutBtn:          { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
    userInfo:           { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
    avatar:             { width: 50, height: 50, borderRadius: 25, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
    avatarText:         { fontSize: 18, fontWeight: '800', color: '#fff' },
    userName:           { fontSize: 16, fontWeight: '700', color: '#fff' },
    userEmail:          { fontSize: 14, color: 'rgba(255,255,255,0.8)' },
    tabs:               { flexDirection: 'row', gap: 8 },
    tab:                { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 10, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.1)' },
    tabActive:          { backgroundColor: 'rgba(255,255,255,0.25)' },
    tabText:            { fontSize: 13, fontWeight: '600', color: 'rgba(255,255,255,0.6)' },
    tabTextActive:      { color: '#fff' },
    content:            { flex: 1 },
    tabContent:         { padding: 20 },
    tabHeader:          { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
    sectionTitle:       { fontSize: 20, fontWeight: '800', color: '#333', marginBottom: 12 },
    addBtn:             { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#6c2bd9', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8 },
    addBtnText:         { fontSize: 13, fontWeight: '700', color: '#fff' },
    emptyText:          { fontSize: 14, color: '#999', textAlign: 'center', marginTop: 20 },
    statsGrid:          { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    statCard:           { width: '48%', backgroundColor: '#fff', borderRadius: 12, padding: 16, borderLeftWidth: 4 },
    statValue:          { fontSize: 28, fontWeight: '800', color: '#333', marginTop: 8 },
    statLabel:          { fontSize: 13, color: '#666', marginTop: 4 },
    card:               { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 12 },
    cardSuspended:      { opacity: 0.7, borderWidth: 1.5, borderColor: '#ffe4cc' },
    cardSelected:       { borderWidth: 2, borderColor: '#6c2bd9', backgroundColor: '#faf8ff' },
    cardHeader:         { flexDirection: 'row', alignItems: 'center', gap: 12 },
    cardAvatar:         { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
    cardAvatarText:     { fontSize: 14, fontWeight: '800' },
    cardTitle:          { fontSize: 16, fontWeight: '700', color: '#333', marginBottom: 2 },
    cardMeta:           { fontSize: 13, color: '#666' },
    cardFooter:         { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginTop: 10 },
    cardActions:        { flexDirection: 'row', gap: 6, marginLeft: 'auto' },
    actionBtn:          { width: 34, height: 34, borderRadius: 17, backgroundColor: '#f0f4ff', borderWidth: 1, borderColor: '#dce8ff', alignItems: 'center', justifyContent: 'center' },
    actionBtnSuccess:   { width: 38, height: 38, borderRadius: 19, backgroundColor: '#e8f5e9', borderWidth: 1, borderColor: '#c8e6c9', alignItems: 'center', justifyContent: 'center' },
    actionBtnWarning:   { width: 38, height: 38, borderRadius: 19, backgroundColor: '#fff8f0', borderWidth: 1, borderColor: '#ffe4cc', alignItems: 'center', justifyContent: 'center' },
    roleBadge:          { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    roleBadgeText:      { fontSize: 12, fontWeight: '700', color: '#fff' },
    suspendedBadge:     { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#fff8f0', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    suspendedBadgeText: { fontSize: 11, fontWeight: '600', color: '#ff9500' },
    protectedBadge:     { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#f0e8ff', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    protectedText:      { fontSize: 11, fontWeight: '600', color: '#6c2bd9' },
    statusBadge:        { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    statusBadgeText:    { fontSize: 12, fontWeight: '700' },

    // Historique abonnements
    historySection:     { marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: '#eee' },
    historyTitle:       { fontSize: 14, fontWeight: '700', color: '#333', marginBottom: 10 },
    subscriptionItem:   { backgroundColor: '#f8f8f8', borderRadius: 8, padding: 10, marginBottom: 8 },
    subLine:            { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
    subPlan:            { fontWeight: '700', color: '#333', fontSize: 14 },
    subStatus:          { fontSize: 13, fontWeight: '600' },
    subDates:           { color: '#666', fontSize: 12 },
    subPrice:           { color: '#6c2bd9', fontWeight: '700', marginTop: 4, fontSize: 13 },
    emptyHistory:       { color: '#999', fontStyle: 'italic', textAlign: 'center', paddingVertical: 16 },

    // Overlay / Modals
    overlay:            { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
    overlayBottom:      { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    confirmBox:         { backgroundColor: '#fff', borderRadius: 20, margin: 30, padding: 28, alignItems: 'center', width: '85%' },
    confirmIconWrap:    { width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
    confirmTitle:       { fontSize: 18, fontWeight: '800', color: '#333', marginBottom: 10 },
    confirmMsg:         { fontSize: 14, color: '#666', textAlign: 'center', lineHeight: 22, marginBottom: 20 },
    confirmBold:        { fontWeight: '800', color: '#333' },
    confirmRow:         { flexDirection: 'row', gap: 12, width: '100%' },
    sheetBox:           { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '90%' },
    sheetHeader:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20, borderTopLeftRadius: 24, borderTopRightRadius: 24 },
    sheetHeaderLeft:    { flexDirection: 'row', alignItems: 'center', gap: 12 },
    sheetIconWrap:      { width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
    sheetTitle:         { fontSize: 17, fontWeight: '800', color: '#fff' },
    sheetSubtitle:      { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
    sheetCloseBtn:      { width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(255,255,255,0.15)', alignItems: 'center', justifyContent: 'center' },
    sheetBody:          { padding: 20, maxHeight: 420 },
    sheetFooter:        { flexDirection: 'row', gap: 12, padding: 20, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
    infoBanner:         { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#f0e8ff', borderRadius: 10, padding: 12, marginBottom: 20 },
    infoBannerText:     { flex: 1, fontSize: 13, color: '#6c2bd9', fontWeight: '500' },
    formRow:            { flexDirection: 'row' },
    formGroup:          { marginBottom: 16 },
    formLabel:          { fontSize: 13, fontWeight: '700', color: '#333', marginBottom: 8 },
    inputWrap:          { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f7f7f7', borderRadius: 10, borderWidth: 1.5, borderColor: '#eee', paddingHorizontal: 12, height: 48 },
    inputError:         { borderColor: '#ff3b30', backgroundColor: '#fff8f8' },
    inputIcon:          { marginRight: 8 },
    input:              { flex: 1, fontSize: 14, color: '#333' },
    eyeBtn:             { padding: 4 },
    textAreaWrap:       { backgroundColor: '#f7f7f7', borderRadius: 10, borderWidth: 1.5, borderColor: '#eee', padding: 12, minHeight: 90, width: '100%' },
    textArea:           { fontSize: 14, color: '#333', textAlignVertical: 'top', minHeight: 70 },
    errorText:          { fontSize: 12, color: '#ff3b30', marginTop: 4 },
    roleList:           { gap: 10 },
    roleOption:         { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 12, borderWidth: 2, borderColor: '#eee', backgroundColor: '#fff' },
    roleOptionIcon:     { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
    roleOptionHeader:   { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 2 },
    roleOptionLabel:    { fontSize: 15, fontWeight: '700', color: '#333' },
    roleOptionDesc:     { fontSize: 12, color: '#999' },
    currentBadge:       { backgroundColor: '#e8f5e9', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
    currentBadgeText:   { fontSize: 10, fontWeight: '700', color: '#2e7d32' },
    radioOuter:         { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#ddd', alignItems: 'center', justifyContent: 'center' },
    radioInner:         { width: 10, height: 10, borderRadius: 5 },
    btnOutline:         { flex: 1, height: 50, borderRadius: 12, borderWidth: 1.5, borderColor: '#ddd', alignItems: 'center', justifyContent: 'center' },
    btnOutlineText:     { fontSize: 15, fontWeight: '700', color: '#666' },
    btnSolid:           { flex: 2, height: 50, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    btnSolidText:       { fontSize: 15, fontWeight: '800', color: '#fff' },
    refreshBtn:         { width: 36, height: 36, borderRadius: 18, backgroundColor: '#f0e8ff', alignItems: 'center', justifyContent: 'center' },
});